import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Container from "@/components/Container";
import SideMenu from "@/components/SideMenu";
import HeaderBar from "@/components/HeaderBar";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/DisableDraftMode";


const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

{(await draftMode()).isEnabled && (<><DisableDraftMode/>
<VisualEditing />

</>)}


        <HeaderBar />
        {children}
        <SideMenu  />
        <SanityLive/>
      </body>
    </html>
    </ClerkProvider>
  );
}
